### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by abdulrahmanshr75** [BertrandConxy/umuhanzi-concert-website#3]

**Comment by abdulrahmanshr75** [comment]
Awsome work 💯 
I suggest that you don't need to repeat the commits like when you corrected the image you have committed many commits about the page.
Excellent job overall 🔥 🔥

**Comment by IfzaRasool** [comment]
You have done a Great job on Your Capstone Project👏
There are no issues to be addressed.

**Comment by BertrandConxy** [comment]
Thank you @IfzaRasool  and @abdulrahmanshr75. I really appreciate your reviews. I am going to improve my design like on the margin-bottom of the showcase section and in other parts. so as to make it perfect.
